# SPDX-FileCopyrightText: 2022 Nicolás Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
