@PACKAGE_INIT@

set_and_check(KSeExpr_DIR @PACKAGE_CMAKE_INSTALL_PREFIX@)
set_and_check(KSeExpr_LIBRARY_DIRS @PACKAGE_CMAKE_INSTALL_LIBDIR@)
set_and_check(KSeExpr_INCLUDE_DIRS @PACKAGE_CMAKE_INSTALL_INCLUDEDIR@)

include("${CMAKE_CURRENT_LIST_DIR}/KSeExprTargets.cmake")

set(KSeExpr_FOUND TRUE)
